# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('currency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(max_length=6)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.LineItem')),
            ],
        ),
        migrations.CreateModel(
            name='Muncipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='keywords',
            name='detail',
            field=models.ManyToManyField(to='explorer.LineItem'),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.LineItem'),
        ),
        migrations.AddField(
            model_name='closuretable',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='explorer.LineItem'),
        ),
        migrations.AddField(
            model_name='closuretable',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant', to='explorer.LineItem'),
        ),
    ]
