# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muncipality',
            name='municipal_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
