# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_muncipality_municipal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal_name', models.CharField(max_length=100)),
                ('fir_name', models.CharField(max_length=100)),
                ('municipal_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Muncipality',
        ),
    ]
