# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_auto_20161126_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(max_length=6)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Municipality')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='costdetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='parent',
        ),
        migrations.AlterField(
            model_name='closuretable',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='explorer.Node'),
        ),
        migrations.AlterField(
            model_name='closuretable',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant', to='explorer.Node'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='detail',
            field=models.ManyToManyField(to='explorer.Node'),
        ),
        migrations.DeleteModel(
            name='CostDetails',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.AddField(
            model_name='entrydetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Node'),
        ),
    ]
